# Site settings
title: Ashani's Blog...
email: ashaniray@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About me: I am a software enginner/achitect graduated from IIT Kharagpur.
  My interests include music, philosophy, mathematics and chess.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ashaniray.github.com" # the base hostname & protocol for your site
twitter_username: ashaniray
github_username:  ashaniray

# Build settings
markdown: kramdown
